AndelaOSP/Andela-Socials

.gitignore, client/tests/cypress/integration/components/HomePage.spec.jsx, cypress.env.json.sample, cypress.json, package.json, yarn.lock
This PR setup cypress for e2e and integration testing.
- Setup cypress to test react components, redux store and also for e2e tests.
- Add a test file to test with cypress
- This  setup makes it possible for team members  to write tests for the application.
There was no way to determine the quality of the applictaion due to unavailabilty of any test setup in the project.
- Pull this branch
- Install dependencies
- Start application
-  Run test with `npm test` command
[#158218914](https://www.pivotaltracker.com/story/show/158218914)
N/A
=> #158218914 Setup cypress for testing

client/.stylelintrc.json, package.json, yarn.lock
This PR setup stylelint for scss files in the client folder.
- Add stylelint configuration
- Add npm scripts to automate running linting
There was no way to enforce a uniform format of writing scss and also ensure following of best practices when writing scss. 
- Pull this branch to your local
- Install all dependencies with yarn
- Run `yarn run style-lint` to run lint on all scss file
[#158495467](https://www.pivotaltracker.com/story/show/158495467)
N/A
N/A
=> #158495467 Setup scss linting

.eslintignore, .eslintrc.json, .gitignore, .prettierrc.json, client/components/Events/index.js, package.json, yarn.lock
Add prettier for code formatting before a commit
Setup a code linter
N/A
edit any file in the frontend then save, git add the file, commit the changes, the changes made will be formatted automatically.
[#158253393](https://www.pivotaltracker.com/story/show/158253393)
N/A
=> #158253393 - Setup a code linter

README.md, client/yarn.lock, dump.sh, init.sh, makefile, scripts/createdb.sh, scripts/dump.sh, scripts/init.sh, scripts/setup.sh, scripts/start.sh, server/a_socials/settings/dev.py, server/start-server.sh
=> create scripts folder and update readme

README.md
- Updates README file
Adds instructions for setting up of the specific node version used within the project to the readme
This can be tested by following the updated instructions in the README
[#158290993](https://www.pivotaltracker.com/story/show/158290993)
=> #158290993 Update Readme 

client/components/HomePage/LoginPage.js, client/index.js, client/public/index.html
=> fix google login

.codeclimate.yml, README.md
It Integrates Code Climate with GitHub repo to check all raised PRs for code quality
- Add a .codeclimate.yml file in the root of the repo
- Add pep8 plugin in .codeclimate.yml
- Add exclude patterns in .codeclimate.yml
- Add maintainability badge and Test Badge to ReadMe file
Check this PR
None
None
=> #158965920 Set up Codeclimate 

server/api/models.py, server/api/utils/auth.py, server/api/utils/backgroundTaskWorker.py, server/api/utils/backgroundWorker.py
It updates user account information (on login) with background tasks
- Create a  resuable `backgroundworker` class in `server/api/utils`
- Make `check_diff` function to be an `async function`
- Update `get_user_profile` method to `get_and_update_user_profile`
- Update `user_profile.check_diff`  in `get_and_update_user_profile` to run in background mode.
- Add valid user token to the request header
- Run `python server/manage.py runserver`
- Hit any route
None
=>  #159070958 Fix update user on login

.eslintrc.json, client/.babelrc, client/package.json, client/webpack.config.dev.js, client/webpack.config.prod.js, client/yarn.lock
updates babel and eslint config
- extract babel config from webpack config into its own file
- update babel and eslint config
Our current babel config doesn't support the latest features in javascript like using arrow functions in classes
- Pull this branch to your local
- Install all dependencies with yarn
- add an arror function method to a class then run `yarn start:dev`
[#159218737](https://www.pivotaltracker.com/story/show/159218737)
N/A
=> #159218737 Update babel config

client/assets/base/globals.scss, client/assets/components/index.scss, client/assets/components/modalContainer.scss, client/assets/pages/homepage.scss, client/assets/style.scss, client/assets/tools/variables.scss, client/components/App.js, client/components/Modals/ModalContainer.js, client/components/Modals/ModalContext.js
This creates the base modal component
N/A
this helps to ensure a consistent way of using/(dis)activating modals
N/A
[#159389843](https://www.pivotaltracker.com/story/show/159389843)
=> #159389843 reusable modal component

.editorconfig, server/a_socials/settings/__init__.py, server/a_socials/settings/base.py, server/api/models.py, server/api/utils/auth.py, server/api/views.py, server/graphql_schemas/category/schema.py, server/graphql_schemas/event/schema.py, server/graphql_schemas/interest/schema.py
Fixes backend Code Climate issue
- Fix all backend issues raised by Code Climate.
- Fix graphQL-schema indentation issue.
- Edit the .editorconfig to indent .py with tabs(4) and .js with spaces
N/A
N/A
[#159134155](https://www.pivotaltracker.com/story/show/159134155)
=> [chore]: Fix backend code climate issues #159134155

server/graphql_schemas/event/schema.py, server/graphql_schemas/interest/schema.py, server/graphql_schemas/tests/attend/base.py, server/graphql_schemas/tests/attend/snapshots/snap_test_mutations.py, server/graphql_schemas/tests/attend/snapshots/snap_test_queries.py, server/graphql_schemas/tests/attend/test_mutations.py, server/graphql_schemas/tests/attend/test_queries.py, server/graphql_schemas/tests/category/base.py, server/graphql_schemas/tests/category/snapshots/snap_test_queries.py, server/graphql_schemas/tests/category/test_queries.py, server/graphql_schemas/tests/events/base.py, server/graphql_schemas/tests/events/snapshots/snap_test_mutations.py, server/graphql_schemas/tests/events/snapshots/snap_test_queries.py, server/graphql_schemas/tests/events/test_mutations.py, server/graphql_schemas/tests/events/test_queries.py, server/graphql_schemas/tests/interest/base.py, server/graphql_schemas/tests/interest/snapshots/snap_test_mutations.py, server/graphql_schemas/tests/interest/snapshots/snap_test_queries.py, server/graphql_schemas/tests/interest/test_mutations.py, server/graphql_schemas/tests/interest/test_queries.py
* Adds Tests for all available graphql functionality
* Fixed broken functionality and test snapshots.
* This can be tested by either running: 
` python server/manage.py test server/graphql_schemas/test`
or
`tox`
[#159071064](https://www.pivotaltracker.com/story/show/159071064)
=> [Chore #159071064] Adds and  Fixes tests for all GraphQL functionality.

server/a_socials/urls.py, server/api/urls.py, server/graphql_schemas/urls.py
* Adds Namespaces and names to /api/urls.py , graphql-schemas/urls.py and a_social/urls.py
* It is always good practise to have namespaces and names on urls to avoid conflicts when trying to access urls that might have similarly named urls.
* Run `server/manage.py test` to confirm the changes did not break any current functionality.
[159498643](https://www.pivotaltracker.com/story/show/159498643)
=> [Chore #159498643] Adds Namespaces and names to django urls 

cypress.json, server/a_socials/settings/base.py, server/api/slack.py, server/graphql_schemas/tests/events/snapshots/snap_test_mutations.py, server/graphql_schemas/utils/cron_jobs.py, server/requirements.txt
- Adds functionality that enables members in a category recieve notification when new members join a group.
- Modify notify user slack function to send direct messages
- Add job to notify members when new users joins daily
- Members in a category have no means of knowing who joins the categories they are part of. This implementation enables the existimbers get notified of members who join a category each day.
- After the necessary user, category and interest tables have been populated appropriately.
- Run `pip install -r server/requirements.txt`
- Run `python server/manage.py crontab add`.
- Run `python server/manage.py crontab show`.
- Run `cron -e` to verify the job is created.
- #159004381
=> #159004381 Notify members when user joins category.

client/assets/components/index.scss, client/assets/components/spinner.scss, client/utils/Spinner.js, client/utils/loadComponent.js
It creates a custom spinner component
- Create a custom spinner component
- Add spinner height and width for reusability
- Replace a div element with loading content in LoadComponent with Spinner component
None
- Run `npm run start:dev`.
- Change network speed to slow 3g in chrome browser.
https://www.pivotaltracker.com/story/show/159670611
None
=>  #159670611 Create a custom spinner component

client/actions/eventActions.js, client/actions/socialClubActions.js, client/components/Modals/ModalContainer.js, client/utils/api.js
- Attempts to fix frontend code climate issues
- Refactor some lines of code reported as issue on codeclimate
- Add central axios call for the actions, just to change function signature
- I noticed some of the issues on codeclimate can be ignored as there is no need for refactoring
- #59134160
=> chore: fix frontend code climate issues

client/assets/base/globals.scss, client/assets/colors.scss, client/assets/components/index.scss, client/assets/components/navbar.scss, client/assets/pages/index.scss, client/assets/pages/login.scss, client/assets/style.scss, client/components/common/NavBar.js, client/pages/Login/LoginPage.jsx, client/routes.js
This PR delivers a small portion of the top navigation bar component.
Create and style the bottom section of the nav bar component.
This task is part of the "Create NavBar" task on PT. However, we decided to split it into two parts.
N/A
[#159075054](https://www.pivotaltracker.com/n/projects/2174978/stories/159075054)
=> #159075054 Create lower section of the Navbar component.

server/graphql_schemas/schema.py, server/graphql_schemas/tests/events/snapshots/snap_test_mutations.py, server/graphql_schemas/tests/users/base.py, server/graphql_schemas/tests/users/snapshots/snap_test_queries.py, server/graphql_schemas/tests/users/test_queries.py, server/graphql_schemas/users/schema.py
- Creates User node
- This feature allows us to access the user model with GraphQl
- N/A
N/A
#159819055
=> #159819055 Create User node

client/assets/components/_event-card.scss, client/assets/components/index.scss, client/assets/pages/_events-page.scss, client/components/cards/EventCard.jsx, client/components/common/NotificationCenter.js, client/fixtures/events.js, client/fixtures/notifications.js, client/index.js, client/pages/Event/EventsPage.jsx
It creates an event gallery component.
* Create calendar component
* Create event fixtures
None
Route to `/events`
https://www.pivotaltracker.com/story/show/159853979
=> #159853979 Create event gallery component 

client/assets/pages/_events-page.scss, client/components/common/CustomDropDown.js, client/components/filter/EventFilter.js, client/package.json, client/pages/Event/EventsPage.jsx
- Creates filter component
- Create custom dropdown component
- Create event filter component
- Add scss
- Start application and visit `/events`
- https://www.pivotaltracker.com/n/projects/2174978/stories/159892131
=> feat(filter): create filter component

client/assets/base/globals.scss, client/assets/components/_button.scss, client/assets/components/index.scss, client/assets/components/navbar.scss, client/assets/pages/_events-page.scss, client/assets/tools/variables.scss, client/pages/Event/EventsPage.jsx
- It creates event footer load-more component.
- Create load more button component
- Add scss style for the load-more component.
- Fix some alignment and background colour issues
None
- Run `np run start:dev` and route to `/events`
- https://www.pivotaltracker.com/story/show/159985290
=> #159892131 Create event load more component

client/yarn.lock, docker/release/docker-compose.yml, docker/release/server/Dockerfile, docker/server/Dockerfile, docker/test/Dockerfile, docker/test/docker-compose.yml, docker/test/wait_for_db.sh, scripts/test.sh
Add new docker files for release and deployment of the Backend to GCP.
Dockerized steps to simplify the steps to build a release image to be deployed on GCP
Run docker-compose file using `docker-compose -f docker/release/docker-compose.yml build` it will build an image. To test the image, run `docker-compose -f docker/release/docker-compose.yml up`. Check the localhost:8000 to see the status of the image.
=> Backend Docker Release

server/api/models.py, server/api/slack.py, server/api/tests/test_auth.py, server/api/views.py
It fixes bug create and update Andela_user_profile
* Change get slack_id return value to slack_id instead of slack_display_name
* Fix bug in create_user_profile method  
* Fix bug in get_and_update_user_profile method
N/A
Run `python server/manage.py runserver`
Try any of the Graphql queries with a valid token.
https://www.pivotaltracker.com/story/show/160127959
N/A
=> # 160127959 Fix bug in create and update Andela_user_profile

client/actions/graphql/categoryGQLActions.js, client/components/common/Calendar.js, client/components/common/CustomDropDown.js, client/components/filter/EventFilter.js, client/pages/Event/EventsPage.jsx
- Connect the filter components to filter events on dashboard
- Connect calendar component
- Connect Filter component
- run the application and visit `/events`
- https://www.pivotaltracker.com/n/projects/2174978/stories/160230819
=> Ft connect filter componenet 158761349

client/Graphql/Queries/EventListGQL.js, client/assets/components/_eventNotFound.scss, client/assets/components/index.scss, client/components/EventNotFound.jsx, client/components/cards/EventCard.jsx, client/components/common/NotFound.js, client/pages/Event/EventsPage.jsx
It fixes a bug in the get-events-list implementation.
* Add featureImage to get event list graphQL query.
* Create EventNotFound Component.
N/A
Browse `/events`
https://www.pivotaltracker.com/story/show/160282500
=> #160282500 Fix get events list implementation.

client/components/filter/EventFilter.js
-  Fix CSS bug with apply button
=> Fix apply button css

client/pages/Dashboard/index.jsx
- Fix 404 shown when dashboard is clicked
- **_Current Behavior_**
- - Clicking dashboard shows 404
- **_Expected Behavior_**
- - Clicking dashboard should show events dashboard page
=> Add dashboard as landing page

client/pages/Dashboard/index.jsx, client/pages/Event/EventsPage.jsx
- fix logout/login error printed on the console
- logout and login again with the console opened
- 160411407
=> Fix errors on dashboard and eventpage

client/Graphql/Queries/EventListGQL.js, client/actions/constants.js, client/actions/graphql/eventGQLActions.js, client/assets/components/_event-card.scss, client/assets/components/_search-modal.scss, client/assets/components/index.scss, client/components/Modals/SearchModal.jsx, client/components/cards/EventCard.jsx, client/components/common/Header.js, client/components/common/NavBar.js, client/components/common/SearchBar.js, client/pages/Event/EventsPage.jsx, client/reducers/eventReducers.js, client/reducers/index.js, client/reducers/initialState.js, client/utils/mapListToComponent.js, server/graphql_schemas/event/schema.py
It designs and implements event search.
* Design search Modal.
* Implement search functionality.
None
Browse `/events`.
https://www.pivotaltracker.com/story/show/160343193
=> #160343193  Design and Implement event search

client/assets/components/common/form.scss, client/assets/pages/_events-page.scss, client/components/Forms/EventForm.js, client/components/common/Form/DateTimePicker.js, client/components/common/Form/InputField.js, client/components/common/Form/TimePicker.js, client/components/common/Form/UploadField.js, client/components/common/Form/propsDefs.js, client/components/common/IncrementalSelect.js
This adds additional fields for start and end date fields to the create event modal.
- create components for selecting time and date.
- add start and end date fields
- The event-create forms should now have the start date and end date fields
[#160244723](https://www.pivotaltracker.com/story/show/160244723)
=> [WIP] Add Additional Create Event Fields

client/Graphql/Mutations/CreateEventGQL.js, client/actions/graphql/eventGQLActions.js, client/components/TestActions/TestActions.js
It updates create event mutation with new fields
Update client mutation with new fields added to create event
N/A
N/A
#160388327
N/A
=> #160388327  Update create event mutation with new fields

client/actions/graphql/eventGQLActions.js, client/components/Forms/EventForm.js, client/components/Modals/ModalContainer.js, client/pages/Dashboard/index.jsx, client/pages/Event/EventsPage.jsx, client/reducers/eventReducers.js
- Connect the create form to store
- click create event button
- 160448972
=> Connect create form to store

scripts/setup.sh, server/start-server.sh
It updates start scripts to reflect changes in fixtures
N/A
N/A
#160495556
N/A
=> #160495556 - Update script with fixtures

client/assets/pages/_events-page.scss, client/components/Forms/EventForm.js, client/pages/Dashboard/index.jsx
- Add category to create event form
- Add customDropDown to events form
- Populate customDropDown with data from db
- 160496748
=> Add category to events form

client/assets/pages/_events-page.scss, client/components/Forms/EventForm.js, client/package.json
- Add timezone to events form
- Add timezone to events form
- #160473989
=> Add timezone

client/Graphql/Queries/EventGQL.js, client/actions/graphql/eventGQLActions.js, client/pages/Dashboard/index.jsx, client/pages/Event/EventDetailsPage.jsx, client/reducers/eventReducers.js, client/reducers/index.js, client/yarn.lock
*  Connects the data endpoint(GraphQL) to the event details component.
*  Fixes route passed props to events details from dashboard component
*  Finishes Connecting Event Details to GraphQL
- The task was to link the events details page to the GraphQL endpoint so that it fetches data correctly.
* run the app and navigate to `/events/:eventId`,  or navigate to the events page/dashboard and click on an event.
[#160244758](https://www.pivotaltracker.com/story/show/160244758)
=> #160244758 Connects Events Details to GraphQL 

server/api/models.py
It ensures state been returned is been saved 
Fix race condition in user_profile_update save
N/A
N/A
#160739565
=> #160739565 Fix calendar invite state issue

client/pages/Dashboard/index.jsx
- fix empty category list on login
- Sign out and sign in again, click on create event, and check click on category
-160754401#
=> Fix category empty list on login

client/pages/Event/EventsPage.jsx
- Brings back startdate for event dashboard to show events of the current date
- Visit dashboard
- #160767492
=> Add back startdate

client/components/Forms/EventForm.js, client/components/common/Form/TimePicker.js
Fixes code quality issues introduced by 160244723.
- Maximise re-usability and abstractions in the codebase.
- codeclimate issues should no longer exist.
[160244723](https://www.pivotaltracker.com/story/show/160244723)
=> Codeclimate issues introduced by 160244723

server/graphql_schemas/event/schema.py
It ensures events are still been created even if a user's calendar is not authorized
Save event on calendar error
Earlier, event details are been lost after been redirected to authorize their google calendar
N/A
#160846610
N/A
=> #160846610 Save event details on calendar error

server/graphql_schemas/event/schema.py
- Add timezone to update schema
- #161014718
=> Add timezone to update schema

client/components/common/Form/DateTimePicker.js
Fix bug with calendar closing once clicked
Fix bug with calendar closing once clicked
N/A
- Log in to the app
- click on the create event floating button
- attempt to select a start date and end date of the event
[161071844](https://www.pivotaltracker.com/n/projects/2174978)
=> #161071844 Fix Bug With Calendar Closing Once Clicked

client/components/Forms/EventForm.js, client/pages/Dashboard/index.jsx, client/pages/Event/EventDetailsPage.jsx
- add eventID to update event
- add eventID to update event
- Refactor code to differentiate between updateEvent and createEvent
- Edit event you own, change the image and any other field.
- #161109589
=> add eventID to update event

client/Graphql/Queries/EventGQL.js, client/Graphql/Queries/EventListGQL.js
- Fix apollo client error
- click on an event
- leave the event by going to dashboard
- select a date that has event
- #161178571
=> Add id to objects

README.md
=> Fix Markdown format

client/assets/pages/_events-page.scss, client/assets/tools/variables.scss
This PR makes the placeholder text in the application dropdown visible
Increase the font size of the placeholder
N/A
* Login to the app
* Go to any dropdown
* The dropdown placeholder should be visible
[161060171](https://www.pivotaltracker.com/story/show/161060171)
=> #161060171 Make dropdown placeholder  text more visible

.gitignore, scripts/configureVirtualEnv.sh, scripts/setup.sh, scripts/start.sh
- Consolidates all common virtual environment functionalities to a single script, `scripts/configureVirtualEnv.sh`
- Adds more flexibility and functionality to virtual env manipulation.
- Run `bash scripts/setup.sh` from your terminal to set up the project.
- Run `bash scripts/start.sh` from your terminal to start the app.
Finishes [#161057497](https://www.pivotaltracker.com/story/show/161057497)
=>  #161057497 Chore allow creation and activation of virtual environments

client/assets/pages/_event_details-page.scss, client/components/Forms/DeleteForm.js, client/components/Modals/ModalContainer.js, client/components/Modals/ModalContext.js, client/pages/Event/EventDetailsPage.jsx
- Add delete UI
- Add delete Modal
- View event as owner,
- Click the delete button
- 161617538
=> Implement delete event UI

server/api/views.py
Fixes failing tests on circle CI
Since the environment has been set to production on circleCI, it tries to generate a template with Django but this is no longer needed since we now have different
=> Fix failing tests on circleCI

client/assets/components/index.scss, client/assets/components/navbar.scss, client/assets/components/sideNav.scss, client/components/common/NavBar.js, client/components/common/SideNav.js
It ensures the navbar is responsive across all the devices.
The navbar should be responsive across all the devices.
N/A
#161058307
=> #161058307 - Make nav-bar responsive

client/actions/graphql/eventGQLActions.js, client/assets/components/index.scss, client/assets/components/navbar.scss, client/assets/components/sideNav.scss, client/components/Forms/DeleteForm.js, client/components/common/NavBar.js, client/components/common/SideNav.js, client/pages/Event/EventDetailsPage.jsx, client/reducers/eventReducers.js, server/api/views.py
- Add delete event functionality
- Navigate to event you own, then click the delete event button
- #161673266
=> Add delete event functionality

server/a_socials/settings/base.py, server/a_socials/settings/dev.py, server/api/admin.py, server/api/context_processors.py, server/api/errors.py, server/api/middleware/jwt_authentication.py, server/api/serializers.py, server/api/tests/test_auth.py, server/api/tests/test_models.py, server/api/utils/backgroundTaskWorker.py, server/api/views.py, server/graphql_schemas/attend/schema.py, server/graphql_schemas/schema.py, server/graphql_schemas/tests/attend/base.py, server/graphql_schemas/tests/attend/test_mutations.py, server/graphql_schemas/tests/attend/test_queries.py, server/graphql_schemas/tests/category/base.py, server/graphql_schemas/tests/category/test_mutations.py, server/graphql_schemas/tests/events/base.py, server/graphql_schemas/tests/events/test_queries.py, server/graphql_schemas/tests/users/test_queries.py, server/graphql_schemas/users/schema.py, server/graphql_schemas/utils/helpers.py, server/graphql_schemas/views.py, server/manage.py
- Removes unnecessary imports and unused variables.
- Adds proper indentation to the code.
- Makes code conform to PEP8 best practices where applicable.
- Finishes [#161579897](https://www.pivotaltracker.com/story/show/161579897)
=> # 161579897 Chore python code cleanup and linting.

client/Graphql/Mutations/AttendEventGQL.js, client/actions/graphql/attendGQLActions.js, client/pages/Event/EventDetailsPage.jsx, client/reducers/eventReducers.js
- Add RSVP event
- Visit event page you are not the creator, click the RSVP button
- #161915146
=> RSVP event

.circleci/config.yml, client/yarn.lock, docker/release/docker-compose.yml, docker/release/server/Dockerfile, scripts/deployFrontend.sh
Update staging deployment scripts to enable faster deployment
=> Fix staging
