.flake8
server/a_socials/settings/dev.py
server/graphql_schemas/event/schema.py
server/graphql_schemas/tests/events/snapshots/snap_test_mutations.py
server/graphql_schemas/tests/events/test_mutations.py
server/graphql_schemas/utils/helpers.py
server/requirements.txt

Add feature for updating/editing an event using GraphQL mutation.
- Add mutation for `updateEvent`.
- Add tests for `updateEvent` mutation.
- Updating events should be implemented as an `Update Event` feature to non-admin end users on the front end. This allows a creator to change the details of their events.
- I have chosen snapshot testing for [these reasons](http://docs.graphene-python.org/en/latest/testing/#snapshot-testing)
- run `python server/manage.py test server/graphql_schemas/tests`
- run the app, navigate to the `/graphql` endpoint and use the `updateEvent` mutation as shown in the gif below.
[#158761270](https://www.pivotaltracker.com/story/show/158761270)

[Feature #158761270] Add event update functionality.

---

server/a_socials/settings/base.py
server/graphql_schemas/attend/schema.py
server/graphql_schemas/event/schema.py
server/graphql_schemas/interest/schema.py
server/graphql_schemas/tests/attend/test_mutations.py
server/graphql_schemas/tests/events/snapshots/snap_test_mutations.py
server/graphql_schemas/tests/events/test_mutations.py

Restructures the graphql mutations to use the graphene auto generated ID, as opposed to using the id that is stored in the database, since the user interacts with the graphene ID from with in the queries
- Change the graphql mutations to use the graphene auto generated ID instead of the id that is stored in the database.
- Fix the inconsistence of using `AndelaUserProfile` when interacting with the user object and when it is not used
Some of graphql mutations are structured to use the database id in order to carry out data updates, yet the user interacts with the id that graphene generates.
- One should run the mutations in [Insomnia](https://insomnia.rest/)
- Run python server/manage.py test server/api/tests/
[#159494668](https://www.pivotaltracker.com/story/show/159494668)
None

[FEATURE #159494668] Fix issues with the graphql endpoints

---

client/.babelrc
client/config/webpack.config.common.js
client/config/webpack.config.dev.js
client/config/webpack.config.prod.js
client/package.json
client/routes.js
client/utils/loadComponent.js

It creates dynamic Imports for code splitting which helps to split our code into various bundles which can then be loaded on demand 
* Install `react-loadable`
* Add babel-polyfill to web pack config entry point
* Add chunkFilename to web pack output config
* create a function that loads component dynamically
* Update Login import in routes.js file
* Update Notfound import in route.js file
Bundling is great, but as our app grows, our bundle will grow too. Especially if we are including large third-party libraries. There is a need to keep an eye on the code we are including in our bundle so that we don’t accidentally make it so large that your app takes a long time to load.
To avoid winding up with a large bundle, it’s good to get ahead of the problem and start splitting our bundle.
Run …

#159544672 Implement route level code splitting 

---

server/api/models.py
server/graphql_schemas/attend/schema.py
server/graphql_schemas/event/schema.py
server/graphql_schemas/interest/schema.py
server/graphql_schemas/tests/events/test_mutations.py
server/graphql_schemas/tests/interest/snapshots/snap_test_mutations.py
server/graphql_schemas/tests/interest/test_mutations.py

Ensures uniformity in naming for categories and events.
- Deprecate usage of `social clubs` for `category`.
- Remove instances where `social event` was used to refer to category.
- Update relevant tests
There was usage of social clubs and category concurrently yet they all refer to the same thing. 
- #159074167

#159074167 Ensure uniformity in naming

---

server/graphql_schemas/attend/schema.py

-  Fix subscribed events query to return the data.
- This fixes an issue raised that the subcribed_events GraphQL query was not  returning data.
- The underlying issue was that the DB query made was filtering through the AndelaUserProfile using the info.context.user(BaseUser) id which eventually returned an empty attend object.
- The fix I used was to move one level into the many-to-many relationship and filter through the AndelaUseProfile using the info.context.user and use the result to filter through the Attend model. 
- Make a Query for subscribed events on the graphql endpoint.
[#159788086](https://www.pivotaltracker.com/story/show/159788086)

[Bug #159788086]Fixing data returned by subscribed events query.

---

server/graphql_schemas/category/schema.py
server/graphql_schemas/schema.py
server/graphql_schemas/tests/category/base.py
server/graphql_schemas/tests/category/snapshots/snap_test_mutations.py
server/graphql_schemas/tests/category/snapshots/snap_test_queries.py
server/graphql_schemas/tests/category/test_mutations.py
server/graphql_schemas/tests/category/test_queries.py
server/graphql_schemas/tests/interest/snapshots/snap_test_mutations.py
server/graphql_schemas/tests/interest/test_mutations.py

- Allows users to create categories from the graphQL endpoint
- When a user posts valid data to  the graphQl category endpoint, then a new category should be created.
- N/A
N/A
#159819111

#159819111 Create category mutation

---

client/pages/Dashboard/index.jsx

- Fix 404 bug
- Add NotFound component to dashboard route
- Before now, Not found is not captured, any unmatched route gives a blank page with only header
- Run app and visit any random route like `/jkhkjhkj`
- #160059733

[bug#160059733]Fix 404 bug]

---

client/yarn.lock
server/graphql_schemas/event/schema.py
server/graphql_schemas/tests/attend/snapshots/snap_test_mutations.py
server/graphql_schemas/tests/attend/snapshots/snap_test_queries.py
server/graphql_schemas/tests/events/base.py
server/graphql_schemas/tests/events/snapshots/snap_test_mutations.py
server/graphql_schemas/tests/events/snapshots/snap_test_queries.py
server/graphql_schemas/tests/events/test_mutations.py
server/graphql_schemas/tests/users/snapshots/snap_test_queries.py

It restricts access to an event invite after the event end time has passed
- While validating the invite link, assert that the end time of the event associated with the invite is in the future
N/A
Run command `tox`
#159750242 User cannot access event invite after event end time
N/A

#159750242 Make invite links expire after event end time

---

client/assets/components/navbar.scss
client/components/common/Header.js
client/components/common/NavBar.js

Adjust menu bar to match mockup
It adjusts MenuBar to match mockup, see screenshot below 👇 
Supposing you have the app setup and running following the README.md
- run `scripts start.sh` while in the project root folder
- Navigate to `http://localhost:9000`.
- You should be able to see a MenuBar with the behavior demonstrated below 
[#160226547](https://www.pivotaltracker.com/n/projects/2174978/stories/160226547)

Bug #160226547: Add hover properties and adjust menu bar

---

server/graphql_schemas/interest/schema.py
server/graphql_schemas/tests/category/test_mutations.py
server/graphql_schemas/tests/interest/snapshots/snap_test_mutations.py
server/graphql_schemas/tests/interest/test_mutations.py

It handles database constraint error from multiple `JoinCategory` queries.
Handle database constraint error from multiple `JoinCategory` queries
N/A
N/A
#160158027

#160158027 Handle database error from multiple JoinCategory queries

---

client/pages/Event/EventsPage.jsx

*   Passes an empty string to the startDate param for fetching lists hence the app fetches all events regardless of the time it is/was supposed to start.
- This is a temporary fix as the bug overflow to the backend this is to keep the current app functional as the whole bug is sorted out.
* run the app and navigate to `/events`,  or `/dashboard`.
[#160726545](https://www.pivotaltracker.com/story/show/160726545)

Temporary fix for Events not showing on dashboard (#160726545)

---

client/assets/components/createEventBtn.scss
client/pages/Dashboard/index.jsx

- Adds `+` icon to `create-event` button.
- Adds `+` icon  to `create-event` button
- None
- Login and view the create event button.
https://www.pivotaltracker.com/story/show/160767501

Add + icon to create button

---

server/graphql_schemas/views.py

It returns the parse_body function removed by [https://github.com/AndelaOSP/Andela-Socials/pull/111/files](https://github.com/AndelaOSP/Andela-Socials/pull/111/files)
Fix error on insonmia and graphql gui
N/A
N/A
N/A

Add back parse_body function

---

client/assets/components/_button.scss
client/components/common/Form/DateTimePicker.js

- make the calendar on create event form hidable by click on a close button
- make the calendar on create-event form hidable by a click outside the calendar component
make the calendar on create event form hidable by click on a close button or outside the calendar component 
N/A
- Log in to the app
- click on the create event floating button
- attempt to select a start date and end date of the event
[#160922537](https://www.pivotaltracker.com/n/projects/2174978/stories/160922537)

make event form hidable by click outside or close button

---

server/graphql_schemas/views.py

- Overwrite the parse_body method to return plain data when the request is not of type 'multipart-form-data`
- The previous parse_body overwrite did not correctly cater for parsing multipart form data.
- With the presence of the previous overwrites, one could not create an event.
- By creating an event using the frontend form and Any other GraphQL Client.
- Fixes [ #161080460]

Fix parse_body to support both GraphQLI and multi-part request

---

.env.sample
README.md
scripts/checkEnv.sh
scripts/start.sh

This PR introduces a script that confirms the existence of the right environment variables by comparing the .env variables present in the .env file with the sample .env file.
This script runs before the start script when `scripts/start.sh` is called and will exit with an error message if the .env hasn't declared all the necessary variables.
. Add `checkEnv.sh` script that performs the check and other necessary helper functions.
. Add `checkEnv.sh` to `start.sh` script, making sure to make it executable.
- Running `start.sh` without an .env file creates one for you with the necessary variables declared. You still have to fill it out though, this only saves you the hassle of having to create an .env file, you have to fill in the values for the variables.
- Running `start.sh` will check that …

#161057741 Add script to confirm environment variables before start.

---

scripts/setup.sh

- Moves database creation into the setup script as a function.
- Remove previously use create_db scripts
- Run `bash scripts/setup.sh` from your terminal.
Finishes [#161058166](https://www.pivotaltracker.com/story/show/161058166)

 #161058166 Chore Allows database creation in setup script

---

client/assets/components/_event-card.scss
client/assets/components/common/form.scss
client/assets/tools/variables.scss

It allows the description to accommodate 3 lines without scrolling - #161060549
It adds space between tags and bottom of the event card - #161058778 
It fixes a missing semicolon error currently on develop.
Allow description to accommodate 3 lines without scrolling.
Add space between tags and bottom of the event card.
#161058778
#161060549
space between tags and bottom of the event card 
description accommodating 3 lines without scrolling

Fix #161058778 and #161060549

---

client/assets/pages/_event_details-page.scss
client/pages/Event/EventDetailsPage.jsx

It makes event details page responsive
Ensure that the view event details page is responsive.
N/A
#161058605
Before
Sketch on figma
Now
web
mobile

#161058605 Make event details page responsive

---

client/package.json
client/pages/Dashboard/index.jsx

Fixes authentication problem that arises on staging because the token is returned in the cookies instead of a query param.
In the case that the token is not already in localStorage, add a check for the token in the cookies and update localStorage if it exists.
This bug was introduced as a result of the Andela api working in multiple ways for localhost and the staging-socials.andela.com URL. In the former, the token was appended as a query param and the latter in the cookies as `jwt-token`
Also, removing the token from localStorage, adding it as `jwt-token` in the cookies and refreshing the landing page, should sign in the user and store the token in localstorage.
Authentication should now work on both development and staging environments. …

Fix authentication bug on staging.

---

client/pages/Dashboard/index.jsx
client/pages/Login/index.js

- In the case that a user is redirected to the login page from within the app, they should be taken back to the previous page they were on.
- The task involves fetching the link to the page in which the user was on before being redirected for authentication and making it the redirect URL on authentication instead of the default `/event` endpoint.
- The URL is passed as a property in the redirect and is checked before creating the redirectUrl.
- If there is a previous page i.e page the unauthenticated user tried to view then they were redirected to log in then that page will be the final destination for the user.
- When logged out try to view any page protected by auth e.g `/dashboard` or use an invite link if one is sent to your email. 
Finishes [#161750629]

#161750629 Feature Persisting redirect url
